#!/usr/bin/env bash
#script that prints bestschool 10 times
x=0
while [ $x -lt 10 ]
do
    if [ $x -eq 3 ]
    then
        echo "bad luck"
    elif [ $x -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    x=$(( x + 1))
done
